### PR TITLE
Revert to makeDOMDriver()

### LINKED ISSUE #51: Revert makeDomDriver back to makeDOMDriver
# Overview
Revert the naming of makeDomDriver -> makeDOMDriver
Revert the documentation to reflect the API change
Update the usage in the tests

# Motivation
Because we love you @staltz 

# References
https://github.com/motorcyclejs/dom/commit/8aeaa425258d7d0b869aa2d2f8f872b601a56a99

### PR DESCRIPTION
**Pull request by TylorS**
Reverts all uses of makeDomDriver back to makeDOMDriver

Closes #51

### CODE REVIEW

**Comment by Frikki** [comment]
@TylorS I need you to rebase your branch and squash these commits into one. Your commit message should be:

```
revert(): change makeDOMDriver -> makeDomDriver

This reverts:
- commit 8aeaa425258d7d0b869aa2d2f8f872b601a56a99
- commit 1f6347c4e0a98fb2f9c11bbd3a1a167b0c4ffae6
- commit 453720500f0de1854364a3b70bac209be9efe7b6
```

See https://github.com/motorcyclejs/motorcycle/blob/master/CONTRIBUTING.md#revert

**Comment by TylorS** [comment]
Ergg, okay. I just don't see a clean way back.
https://github.com/motorcyclejs/dom/commit/b025e75792f5a093b2e76b7006e918d8cac16cd4

**Comment by Frikki** [comment]
@TylorS Still not okay. You need to pay attention to what I wrote and the link. Your commits are now:

```shell
commit 6b06009ef72ac6927466173f903bc3a91a7909ff
Author: TylorS <tlsteinberger167@gmail.com>
Date:   Tue Dec 22 16:44:14 2015 -0500

    Revert "fix(test): fix usage errors"
    
    This reverts commit 453720500f0de1854364a3b70bac209be9efe7b6.

 test/browser/index.js | 48 ++++++++++++++++++++++++------------------------
 1 file changed, 24 insertions(+), 24 deletions(-)

commit 06a376d923ac0be295c9bfd28172093240a3fb82
Author: TylorS <tlsteinberger167@gmail.com>
Date:   Tue Dec 22 16:43:36 2015 -0500

    Revert "fix(): fix makeDomDriver import"
    
    This reverts commit 1f6347c4e0a98fb2f9c11bbd3a1a167b0c4ffae6.

 test/browser/index.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit 969c70b6039991d3427fe5a8fcdc93d3e4b1a991
Author: TylorS <tlsteinberger167@gmail.com>
Date:   Tue Dec 22 16:42:49 2015 -0500

    Revert "chore(README): change MakeDOMDriver -> MakeDomDriver"
    
    This reverts commit 8aeaa425258d7d0b869aa2d2f8f872b601a56a99.

 README.md | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)
```

That’s neither what I wrote, nor what our contribution guideline says, which I linked to. Any header **must** begin with `type(optional scope):`. For reverts it is:

If the commit reverts a previous commit, it should begin with `revert():`, followed by the header of the reverted commit. In the body, it should say: `This reverts commit <hash>.`, where the hash is the SHA of the commit being reverted.

Thus:

```
# First commit

revert(): fix(test): fix usage errors
    
This reverts commit 453720500f0de1854364a3b70bac209be9efe7b6.

# Second commit

revert(): fix(): fix makeDomDriver import
    
This reverts commit 1f6347c4e0a98fb2f9c11bbd3a1a167b0c4ffae6.

# Third commit

revert(): chore(README): change MakeDOMDriver -> MakeDomDriver
    
This reverts commit 8aeaa425258d7d0b869aa2d2f8f872b601a56a99.
```

Now, if the changes actually happened in another commit, they of course shouldn’t be like this. Instead, squash the commits into one and specify it:

```
refactor(): change `makeDomDriver` to `makeDOMDriver`

Closes #51
```

**Comment by Frikki** [comment]
Okay, no worries. I’ do this.

**Comment by Frikki** [comment]
Closing, as PR #53 takes over.

**Pull request closed without merging**
