### PR TITLE
test(perf): Update performance test

### PR DESCRIPTION
**Pull request by TylorS**
Better use of most improves the performance and drastically
reduces visual stutter.

References #44

### CODE REVIEW

**Comment by Frikki** [comment]
@TylorS I am very unsure about how to merge this PR. When I merge *develop* into this branch, it overwrites your changes. I think you need to resolve this locally somehow, as I don’t know which are the correct to keep.

**Comment by TylorS** [comment]
Okay, I'll work on that :+1:

**Comment by TylorS** [comment]
Should be good now

**Comment by Frikki** [comment]
Alright. I’ll give it a go.

**Pull request merged**
