### PR TITLE
Add support for thunks

### LINKED ISSUE #33: Thunk support
# Overview
This library should support thunks as provided by snabbdom.

# Goals
- Export `thunk` from `snabbdom/thunk`
```js
import {thunk} from '@motorcycle/dom'
```
- Add tests ensuring that thunks work properly

# References
TylorS/snabbdom-selector#3

### PR DESCRIPTION
**Pull request by TylorS**
This adds support for selecting and thunks and exports snabbdom/thunk

Closes #33

### CODE REVIEW

**Comment by TylorS** [comment]
This will need to rebase on #32 before being merged as they will conflict.

**Comment by Frikki** [comment]
@TylorS You need to pull develop branch and merge it into your feat/issue-#33 branch and resolve the conflicts. Only you know what to keep and what not to. After that, push again.

**Comment by TylorS** [comment]
:+1:

**Comment by TylorS** [comment]
@Frikki Should be good to go.

**Pull request merged**
